---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(ggtext)

```

```{r}
df <- read_csv("data\\cleaned_data.csv") %>%
  filter(date_downloaded < "2022-04-01")

policy_data = read_csv("data\\policy_data.csv")%>%
  filter(date_downloaded < "2022-04-01")
```

```{r}
grade <- read_csv("data\\grades_data.csv")
grades <- unique(grade$label)
grade_lookup <- read_csv("data\\grade_lookup.csv")
dept_lookup <- read_csv("data\\dept_lookup.csv")

```

#topics
```{r}
cut_off = 0.001
topic_predictions  = read_csv("data\\all_the_predictions.csv") %>%
  group_by(job_ref) %>%
  filter(probs == max(probs)) %>%
  ungroup() %>%
  filter(probs >= cut_off)
```

###Add features
```{r}
df<- df %>% mutate( is_policy = stringr::str_detect(`Type of role`, "Policy|Strategy"))
df<- df %>% mutate( is_analysis = stringr::str_detect(`Type of role`, "Statistics|Operational Research|Social Research|Analytical|Economist"))
df <- left_join(df, topic_predictions)

topic_jobs = df %>% filter(!is.na(policy_area))
```

###Internal vs External
```{r}
proportion_internal <- function(vec){
  
  external_count <- vec[vec %in% c("External")] %>% length()
  cross_gov_count <- vec[vec %in% c("Across government")] %>% length()

return(cross_gov_count/ (cross_gov_count + external_count))
}

```

```{r}

grade_approach_of_subset <- function(data){
  grades = unique(grade$label)
  all_results = data.frame()
  for(this_grade in grades){
    df <- data %>%
      filter(stringr::str_detect(grade, this_grade))
    count = nrow(df)
    internal_prop = proportion_internal(df$approach)
    output = c(this_grade, internal_prop)
    all_results = rbind(all_results, data.frame("grade"=this_grade, "internal_percentage"=internal_prop, "count" = count))
  }
  return(all_results)
}
```

```{r}
all_roles = grade_approach_of_subset(df) %>% mutate(group = "All roles")
policy_strategy = grade_approach_of_subset(df %>% filter(is_policy)) %>% mutate(group = "Policy roles")
analysis = grade_approach_of_subset(df %>% filter(is_analysis)) %>% mutate(group = "Analysis roles")

all_int_props = rbind(all_roles, policy_strategy, analysis) %>%
  left_join(grade_lookup) %>%
  filter(!abbreviation %in% c("Perm Sec", "Other", "Ind","AA", "AO"))

all_ext_props <- all_int_props %>%
  mutate(internal_percentage = 1- internal_percentage,
         approach = "external")
  

all_props = all_int_props %>%
  mutate(approach = "internal") %>%
  rbind(all_ext_props)

```

```{r}
plot = ggplot(data = all_props, aes(x = fct_reorder(abbreviation, order,.desc = TRUE), y = internal_percentage, fill = approach)) +
  geom_bar(stat = "identity", alpha = 0.7) +
  facet_grid(. ~group)+
  coord_flip() + 
  ylim(0,1) +
  scale_fill_manual(values = c("#EDEDED","#72BEBD")) +
  geom_text(aes(label = scales::percent(internal_percentage,accuracy =1), group = "internal"), fontface = "bold",
             position = position_fill(0.5), size = 5, color = "#EDEDED") +
  theme_minimal()+
  ylab("Proportion") + 
  xlab("Grade") + 
  labs(title = "Percentage of adverts that were  <span style='color:#72BEBD;'>only advertised internally</span> <br>(to existing civil servants)<br>April 2020 to March 2022")+
  theme(plot.title= element_markdown(color = "#4C545C", size = 14),
        axis.text = element_text(color = "#4C545C", size = 14),
        axis.title = element_text(color = "#4C545C", size = 14),
        strip.text.x = element_text(color = "#4C545C", size = 14),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.line.x=element_blank(),
    axis.line.y=element_blank(),
    legend.position="none")
plot
```

```{r}
df_with_dept <- df %>%
  filter(is_policy | is_analysis) %>%
  left_join(dept_lookup)

dept_approach <- df_with_dept %>%
  filter(!is.na(`department abbreviation`)) %>%
  group_by(`department abbreviation`) %>%
  summarise(percentage = proportion_internal(approach)) 

all_depts = list()
for(dept in dept_approach$`department abbreviation`){
  dept_df <- df_with_dept %>%filter(`department abbreviation` == dept)
  dept_grade_internal = grade_approach_of_subset(dept_df) %>% mutate(department = dept)
  all_depts = rbind(all_depts, dept_grade_internal)
}

dept_internal_external <- all_depts%>%
  left_join(grade_lookup) %>%
  filter(!abbreviation %in% c("Perm Sec", "Other", "Ind","AA", "AO")) 

all_dept_ext_props <- dept_internal_external %>%
  mutate(internal_percentage = 1- internal_percentage,
         approach = "external")
  
all_dept_props = dept_internal_external %>%
  mutate(approach = "internal") %>%
  rbind(all_dept_ext_props) %>%
  filter(!department %in% c("CDO", "HoP", "SG", "WG"))


```





```{r}
plot = ggplot(data = all_dept_props, aes(x = fct_reorder(abbreviation, order,.desc = TRUE), y = internal_percentage, fill = approach, group = department)) +
  geom_bar(stat = "identity", alpha = 0.7) +
  facet_wrap(~department, ncol = 4)+
  coord_flip() + 
  ylim(0,1) +
  scale_fill_manual(values = c("#EDEDED","#72BEBD")) +
  theme_minimal()+
  ylab("Proportion") + 
  xlab("Grade") + 
  labs(title = "Percentage of adverts that were  <span style='color:#72BEBD;'>only advertised internally</span> (to existing civil servants) April 2020 to March 2022")+
  theme(plot.title= element_markdown(color = "#4C545C", size = 14),
        axis.text = element_text(color = "#4C545C", size = 14),
        axis.title = element_text(color = "#4C545C", size = 14),
        strip.text.x = element_text(color = "#4C545C", size = 14),
        plot.margin = margin(0,1,1,1),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.line.x=element_blank(),
    axis.line.y=element_blank(),
    legend.position="none")
plot
```

#Competencies
```{r}
behaviours <- read_csv("data/behaviours.csv")
behaviour_lookup <- policy_data %>%
  filter(!is.na(Behaviours))

results = data.frame()
for (behav in behaviours$behaviour){
  behaviour_df = behaviour_lookup %>%
    mutate(result = stringr::str_detect(Behaviours, behav),#
           behaviour = behav,
           job_ref = as.character(job_ref)) %>%
    select(job_ref, behaviour, result)
  results = rbind(results,behaviour_df)
}
grade_totals <- grade %>%
  filter(job_ref %in% results$job_ref) %>%
  left_join(grade_lookup, by = c("label" = "grade"))%>%
  distinct(job_ref, group, .keep_all = T) %>%
  group_by(group) %>%
  summarise(n = n(), order= mean(order))

grade_behaviour = grade %>%
  filter(job_ref %in% results$job_ref) %>%
  left_join(grade_lookup, by = c("label" = "grade")) %>%
  distinct(job_ref, group, .keep_all = T) %>%
  full_join(results) %>%
  group_by(group, behaviour) %>%
  summarise(count = sum(result)) %>%
  left_join(grade_totals) %>%
  mutate(perc = count/n)  %>%
  ungroup() %>%
  select(-count, -n) %>%
  filter(group %in% c("EO", "HEO/SEO", "G6/7", "SCS" ))

```

```{r}
plot <- ggplot(data = grade_behaviour, aes(x=fct_reorder(group, order,.desc = TRUE), y=behaviour, fill=perc)) + 
  geom_tile() +
  scale_fill_gradient(low = "#EDEDED",
                      high = "#72BEBD",
                      guide = "colorbar") +
  ylab("Behaviour") + 
  xlab("Grade") +
 geom_text(aes(label = scales::percent(perc,accuracy =1)), fontface = "bold", size = 5, color = "#4C545C")+
  theme(plot.title= element_markdown(color = "#4C545C", size = 14),
        axis.text = element_text(color = "#4C545C", size = 14),
        axis.title = element_text(color = "#4C545C", size = 14),
        strip.text.x = element_text(color = "#4C545C", size = 14),
        plot.margin = margin(0,1,1,1),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    legend.position="none")

plot
```

#Length of time advertised
```{r}


```



#Length of time advertised
```{r}


```



